version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - ./play:/play
    ports:
      - 27017:27017
    networks:
      - net

networks:
  net:
    name: mongodb-net
    driver: bridge